defaults:
  - _self_

exp_number: base  # 実行時に書き換え

data:
  data_root: ../../data
  results_root: ../../results
  train_path: ${data.data_root}/train.csv
  test_path: ${data.data_root}/test.csv
  sample_submission_path: ${data.data_root}/sample_submission.csv
  results_dir: ${data.results_root}/${exp_number}

seed: 42
n_splits: 5
target: SalePrice
